# SentiHotel配置文件

# 数据相关配置
data:
  # 原始数据文件路径
  train_file: "data/raw/train.tsv"  # 训练数据文件，TSV格式（标签\t评论文本）
  stopwords_file: "data/raw/hit_stopwords.txt"  # 停用词文件
  word2vec_model: "data/models/word2vec.txt"  # 预训练词向量模型文件
  
  # 数据处理和缓存目录
  processed_dir: "data/processed"  # 处理后的数据存储目录
  cache_dir: "data/cache"         # 数据缓存目录
  model_dir: "models"             # 模型保存目录

# 数据预处理配置
preprocessing:
  # 交叉验证设置
  n_splits: 5                     # K折交叉验证的折数
  random_seed: 42                 # 随机种子，确保结果可复现
  
  # 文本处理参数
  max_sequence_length: 128        # 序列最大长度，超过将被截断
  test_size: 0.2                 # 验证集比例（在每折中）

# 模型配置
model:
  embedding_dim: 100
  # vocab_size: 50000
  lstm_hidden_size: 64
  proj_size: 32
  lstm_layers: 3
  dropout: 0.2
  batch_size: 128
  epochs: 30
  learning_rate: 0.001
  weight_decay: 0.01
  min_lr: 1e-6
  warmup_epochs: 10
  beta1: 0.9
  beta2: 0.999